version: "3"
services:
  vote-service:
    image: vote-service
    ports:
      - "8084:8084"
    networks:
      - blog-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:5.7
    networks:
      - blog-mysql
    ports:
      - "6033:3306"      
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - /tmp/mysql:/var/lib/mysql      

networks:
  blog-mysql:
  
volumes:
  dbdata:
