version: "3"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb 
    networks:
      - blog-mysql
    ports:
      - "6033:3306"      
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - ./tmp/mysql:/var/lib/mysql      

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - blog-mysql
    depends_on:
      - mysqldb

  post-service:
    image: post-service
    container_name: post-service    
    ports:
      - "8082:8082"
    networks:
      - blog-mysql
    depends_on:
      - mysqldb 

  comment-service:
    image: comment-service
    container_name: comment-service    
    ports:
      - "8083:8083"
    networks:
      - blog-mysql   
    depends_on:
      - mysqldb

  vote-service:
    image: vote-service
    container_name: vote-service    
    ports:
      - "8084:8084"
    networks:
      - blog-mysql
    depends_on:
      - mysqldb

  gateway-service:
    image: gateway-service
    container_name: gateway-service    
    ports:
      - "8080:8080"
    networks:
      - blog-mysql
    depends_on:
      - mysqldb
      
networks:
  blog-mysql:
  

